---
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      pkgbuilds:
        patterns:
          - "/.pkgbuilds/*"
      nvim-plugins:
        patterns:
          - "/.nvim-plugins/*"
      browser-extensions:
        patterns:
          - "/.browser-extensions/*"

  - package-ecosystem: "npm"
    directory: "/.npm-packages"
    schedule:
      interval: "weekly"
    groups:
      npm-packages:
        patterns:
          - "*"
