---
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    target-branch: master # see https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    directory: "/"
    schedule:
      interval: "daily"
    patterns:
      - "/.pkgbuilds/*"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    patterns:
      - "/.nvim-plugins/*"
      - "/.browser-extensions/*"

  - package-ecosystem: "npm"
    directory: "/.npm-packages"
    schedule:
      interval: "weekly"
