# See GitHub's documentation for more information on this file:
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/.nvim-plugins"
    schedule:
      interval: "weekly"
    groups:
      gitsubmodule:
        patterns:
          - "*"
    commit-message:
      prefix: "neovim"


  - package-ecosystem: "gitsubmodule"
    directory: "/.pkgbuilds"
    schedule:
      interval: "weekly"
    groups:
      gitsubmodule:
        patterns:
          - "*"
    commit-message:
      prefix: "aur"
