---
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    target-branch: master # see https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: ".pkgbuilds/*"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: ".nvim-plugins/*"
      - dependency-name: ".browser-extensions/*"

  - package-ecosystem: "npm"
    directory: "/.npm-packages"
    schedule:
      interval: "weekly"
