---
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      nvim-plugins:
        patterns:
          - "/.nvim-plugins/*"
      aur:
        patterns:
          - "/.pkgbuilds/*"

  - package-ecosystem: "npm"
    directory: "/.npm-packages"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"

  - package-ecosystem: "composer"
    directory: "/.composer-packages"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "composer"

  - package-ecosystem: "gomod"
    directory: "/.go-packages"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "go"
