---
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/.pkgbuilds"
    schedule:
      interval: "daily"
    groups:
      aur:
        patterns:
          - "*"

  - package-ecosystem: "gitsubmodule"
    directory: "/.nvim-plugins"
    schedule:
      interval: "weekly"
    groups:
      nvim-plugins:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/.npm-packages"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"

  - package-ecosystem: "gomod"
    directory: "/.go-packages"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "go"
