---
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      nvim-plugins:
        patterns:
          - "/.nvim-plugins/*"
      aur:
        patterns:
          - "/.pkgbuilds/*"

  - package-ecosystem: "npm"
    directory: "/.npm-packages"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "npm"

  - package-ecosystem: "gomod"
    directory: "/.go-packages"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "go"
